language: php

php:
    - 7.2

sudo: false

matrix:
  fast_finish: true

before_script:
  - phpunit --version
  - which phpunit
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=^6"

script:
  - phpunit --version
