language: php

php:
    - 5.3

sudo: false

before_script:
    - export CODESNIFF_PATH=('.' '!' -path "./dev-lib/*" '!' -path "./vendor/*")

script:
    - if [[ -z $CODESNIFF_PATH ]]; then echo 'does not exist'; else echo 'exists!'; fi
    - find "${CODESNIFF_PATH[@]}" \( -name '*.php' -o -name '*.inc' \) -exec php -lf {} \;
